-- Add migration script here
CREATE TABLE WALLPAPERS(
    ID TEXT PRIMARY KEY UNIQUE NOT NULL,
    URL TEXT UNIQUE NOT NULL,
    SHORT_URL TEXT UNIQUE NOT NULL,
    VIEWS INTEGER NOT NULL,
    FAVORITES INTEGER NOT NULL,
    SOURCE VARCHAR(255),
    PURITY VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    DIMENSION_X INTEGER NOT NULL,
    DIMENSION_Y INTEGER NOT NULL,
    RESOLUTION VARCHAR(255) NOT NULL,
    RATIO VARCHAR(255) NOT NULL,
    FILE_SIZE INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL,
    COLORS TEXT[] NOT NULL,
    PATH TEXT NOT NULL,
    THUMB_LARGE TEXT NOT NULL,
    THUMB_ORIGINAL TEXT NOT NULL,
    THUMB_SMALL TEXT NOT NULL
);